# targets:
#   $default:
#     builders:
#       freezed:
#         options:
#           generic_argument_factories: true
#       json_serializable:
#         options:
#           generic_argument_factories: true